export type AiAnalystId = "ai_chips_analyst";

export type AiAnalystTheme = "AI_CHIPS";
export type AiAnalystAccountType = "HUMAN" | "AI_ANALYST";

export type AiAnalystConfig = {
  id: AiAnalystId;
  identity: {
    displayName: string;
    nickname: string;
    accountType: "AI_ANALYST";
    theme: AiAnalystTheme;
    badgeLabel: string;
    bio: string;
  };
  coverage: {
    market: "US";
    tickers: string[];
    thesisScope: string[];
  };
  publication: {
    mode: "MANUAL_APPROVAL" | "AUTO_PUBLISH";
    visibility: "PUBLIC";
    labeling: {
      showAiGeneratedBadge: boolean;
      disclosureShort: string;
      disclosureLong: string;
    };
    cadence: {
      maxNewCallsPerRun: number;
      maxNewCallsPerTradingDay: number;
      mayPublishZeroCalls: boolean;
    };
  };
  generation: {
    provider: "openai";
    model: string;
    promptVersion: string;
    outputVersion: string;
    allowNoCall: boolean;
    evaluateUniverseAsBatch: boolean;
    requiredOutputFields: string[];
  };
  guardrails: {
    openCallPolicy: {
      maxOpenCallsPerTicker: number;
      blockDuplicateTickerWhileOpen: boolean;
    };
    approval: {
      requiresAdminReview: boolean;
    };
    confidence: {
      minPublishConfidence: number;
    };
    thesis: {
      requireCatalyst: boolean;
      requireRiskSection: boolean;
      requireTimeHorizon: boolean;
      maxTitleLength: number;
      maxBodyLength: number;
    };
    tickerEligibility: {
      onlyCoveredTickers: boolean;
    };
  };
  publicContent: {
    howItWorks: {
      summary: string;
      methodology: string[];
      rules: string[];
      limitations: string[];
    };
    profile: {
      coverageUniverseTitle: string;
      methodologyTitle: string;
      limitationsTitle: string;
    };
  };
  internal: {
    scheduling: {
      trigger: "AFTER_EOD_COMPLETED";
      rerunPolicy: "IDEMPOTENT_SINGLE_RUN_PER_DAY";
    };
    prompting: {
      includeOpenCallsSummary: boolean;
      includeMarketSnapshot: boolean;
      includeEligibleTickersOnlyForPublication: boolean;
    };
    observability: {
      savePromptInput: boolean;
      saveRawModelOutput: boolean;
      saveValidationErrors: boolean;
    };
  };
};

export type PublicAiAnalystProfile = {
  id: AiAnalystId;
  badgeLabel: string;
  theme: AiAnalystTheme;
  coverageTickers: string[];
  disclosureShort: string;
  disclosureLong: string;
  howItWorks: AiAnalystConfig["publicContent"]["howItWorks"];
  profileSections: AiAnalystConfig["publicContent"]["profile"];
};

export const aiChipsAnalystConfig: AiAnalystConfig = {
  id: "ai_chips_analyst",
  identity: {
    displayName: "AI Chips Analyst",
    nickname: "ai_chips_analyst",
    accountType: "AI_ANALYST",
    theme: "AI_CHIPS",
    badgeLabel: "AI Analyst",
    bio: "AI analyst focused on AI semiconductor and infrastructure names. Publishes transparent, scoreable calls on a curated chip universe.",
  },
  coverage: {
    market: "US",
    tickers: ["NVDA", "AMD", "AVGO", "TSM", "MU", "MRVL"],
    thesisScope: [
      "ai accelerator demand",
      "datacenter and hyperscaler capex",
      "networking and interconnect demand",
      "memory demand and pricing",
      "foundry and manufacturing leverage",
      "custom silicon and infrastructure exposure",
    ],
  },
  publication: {
    mode: "MANUAL_APPROVAL",
    visibility: "PUBLIC",
    labeling: {
      showAiGeneratedBadge: true,
      disclosureShort: "AI Analyst",
      disclosureLong:
        "This prediction was generated by an AI analyst account and reviewed before publication.",
    },
    cadence: {
      maxNewCallsPerRun: 2,
      maxNewCallsPerTradingDay: 2,
      mayPublishZeroCalls: true,
    },
  },
  generation: {
    provider: "openai",
    model: "gpt-5.4",
    promptVersion: "ai-chips-v1",
    outputVersion: "prediction-draft-v1",
    allowNoCall: true,
    evaluateUniverseAsBatch: true,
    requiredOutputFields: [
      "ticker",
      "direction",
      "thesisTitle",
      "thesis",
      "timeHorizon",
      "confidence",
      "catalyst",
      "signals",
      "risks",
    ],
  },
  guardrails: {
    openCallPolicy: {
      maxOpenCallsPerTicker: 1,
      blockDuplicateTickerWhileOpen: true,
    },
    approval: {
      requiresAdminReview: true,
    },
    confidence: {
      minPublishConfidence: 0.62,
    },
    thesis: {
      requireCatalyst: true,
      requireRiskSection: true,
      requireTimeHorizon: true,
      maxTitleLength: 120,
      maxBodyLength: 10000,
    },
    tickerEligibility: {
      onlyCoveredTickers: true,
    },
  },
  publicContent: {
    howItWorks: {
      summary:
        "AI Chips Analyst is a specialist AI analyst account focused on a curated set of AI semiconductor and infrastructure names.",
      methodology: [
        "Evaluates a curated universe of AI-chip-related tickers after end-of-day market processing completes.",
        "Looks for selective setups with a clear directional thesis, catalyst, and time horizon.",
        "Uses existing open calls as context so it does not duplicate active positions on the same ticker.",
      ],
      rules: [
        "Covers only NVDA, AMD, AVGO, TSM, MU, and MRVL at launch.",
        "Can have only one open call per ticker at a time.",
        "May publish zero calls on days without strong setups.",
        "All calls are labeled as AI Analyst predictions and reviewed before publication.",
      ],
      limitations: [
        "The analyst covers only its listed universe and does not represent the full market.",
        "Published calls reflect model output plus platform review, not certainty.",
        "A strong company is not automatically a daily call; timing and setup matter.",
      ],
    },
    profile: {
      coverageUniverseTitle: "Coverage Universe",
      methodologyTitle: "How This Analyst Works",
      limitationsTitle: "Limitations",
    },
  },
  internal: {
    scheduling: {
      trigger: "AFTER_EOD_COMPLETED",
      rerunPolicy: "IDEMPOTENT_SINGLE_RUN_PER_DAY",
    },
    prompting: {
      includeOpenCallsSummary: true,
      includeMarketSnapshot: true,
      includeEligibleTickersOnlyForPublication: true,
    },
    observability: {
      savePromptInput: true,
      saveRawModelOutput: true,
      saveValidationErrors: true,
    },
  },
};

const AI_ANALYST_CONFIGS: Record<AiAnalystId, AiAnalystConfig> = {
  [aiChipsAnalystConfig.id]: aiChipsAnalystConfig,
};

function readAiAnalystId(userData: Record<string, unknown> | null | undefined): AiAnalystId | null {
  const accountType = userData?.accountType;
  const aiAnalystId = userData?.aiAnalystId;

  if (accountType !== "AI_ANALYST" || typeof aiAnalystId !== "string") {
    return null;
  }

  return aiAnalystId in AI_ANALYST_CONFIGS ? (aiAnalystId as AiAnalystId) : null;
}

export function getAiAnalystConfig(id: AiAnalystId): AiAnalystConfig {
  return AI_ANALYST_CONFIGS[id];
}

export function getAiAnalystPublicProfile(id: AiAnalystId): PublicAiAnalystProfile {
  const config = getAiAnalystConfig(id);

  return {
    id: config.id,
    badgeLabel: config.identity.badgeLabel,
    theme: config.identity.theme,
    coverageTickers: [...config.coverage.tickers],
    disclosureShort: config.publication.labeling.disclosureShort,
    disclosureLong: config.publication.labeling.disclosureLong,
    howItWorks: config.publicContent.howItWorks,
    profileSections: config.publicContent.profile,
  };
}

export function getAiAnalystPublicProfileForUser(
  userData: Record<string, unknown> | null | undefined,
): PublicAiAnalystProfile | null {
  const id = readAiAnalystId(userData);
  return id ? getAiAnalystPublicProfile(id) : null;
}

