export type AiAnalystId = "ai_chips_analyst";

export type AiAnalystTheme = "AI_CHIPS";
export type AiAnalystAccountType = "HUMAN" | "AI_ANALYST";

export type AiAnalystConfig = {
  id: AiAnalystId;
  identity: {
    displayName: string;
    nickname: string;
    accountType: "AI_ANALYST";
    theme: AiAnalystTheme;
    badgeLabel: string;
    bio: string;
  };
  coverage: {
    market: "US";
    tickers: string[];
    thesisScope: string[];
    candidateRequirements: {
      usListedOnly: boolean;
      minMarketCapUsd: number;
    };
  };
  publication: {
    mode: "MANUAL_APPROVAL" | "AUTO_PUBLISH";
    visibility: "PUBLIC";
    labeling: {
      showAiGeneratedBadge: boolean;
      disclosureShort: string;
      disclosureLong: string;
    };
    cadence: {
      maxNewCallsPerRun: number;
      maxNewCallsPerTradingDay: number;
      mayPublishZeroCalls: boolean;
    };
    portfolio: {
      maxOpenPredictions: number;
    };
  };
  generation: {
    provider: "openai";
    model: string;
    promptVersion: string;
    outputVersion: string;
    allowNoCall: boolean;
    evaluateUniverseAsBatch: boolean;
    requiredOutputFields: string[];
  };
  guardrails: {
    openCallPolicy: {
      maxOpenCallsPerTicker: number;
      blockDuplicateTickerWhileOpen: boolean;
    };
    approval: {
      requiresAdminReview: boolean;
    };
    confidence: {
      minPublishConfidence: number;
    };
    thesis: {
      requireCatalyst: boolean;
      requireRiskSection: boolean;
      requireTimeHorizon: boolean;
      maxTitleLength: number;
      maxBodyLength: number;
    };
    tickerEligibility: {
      onlyCoveredTickers: boolean;
    };
  };
  publicContent: {
    howItWorks: {
      summary: string;
      methodology: string[];
      rules: string[];
      limitations: string[];
    };
    profile: {
      coverageUniverseTitle: string;
      methodologyTitle: string;
      limitationsTitle: string;
    };
  };
  internal: {
    scheduling: {
      trigger: "AFTER_EOD_COMPLETED";
      rerunPolicy: "IDEMPOTENT_SINGLE_RUN_PER_DAY";
    };
    prompting: {
      includeOpenCallsSummary: boolean;
      includeMarketSnapshot: boolean;
      includeEligibleTickersOnlyForPublication: boolean;
    };
    observability: {
      savePromptInput: boolean;
      saveRawModelOutput: boolean;
      saveValidationErrors: boolean;
    };
  };
};

export type PublicAiAnalystProfile = {
  id: AiAnalystId;
  badgeLabel: string;
  theme: AiAnalystTheme;
  coverageTickers: string[];
  disclosureShort: string;
  disclosureLong: string;
  howItWorks: AiAnalystConfig["publicContent"]["howItWorks"];
  profileSections: AiAnalystConfig["publicContent"]["profile"];
};

export const aiChipsAnalystConfig: AiAnalystConfig = {
  id: "ai_chips_analyst",
  identity: {
    displayName: "AI Chips Analyst",
    nickname: "ai_chips_analyst",
    accountType: "AI_ANALYST",
    theme: "AI_CHIPS",
    badgeLabel: "AI Analyst",
    bio: "AI analyst focused on AI semiconductor and infrastructure names. Publishes transparent, scoreable calls on a curated chip universe.",
  },
  coverage: {
    market: "US",
    tickers: ["NVDA", "AMD", "AVGO", "TSM", "MU", "MRVL"],
    thesisScope: [
      "ai accelerator demand",
      "datacenter and hyperscaler capex",
      "networking and interconnect demand",
      "memory demand and pricing",
      "foundry and manufacturing leverage",
      "custom silicon and infrastructure exposure",
    ],
    candidateRequirements: {
      usListedOnly: true,
      minMarketCapUsd: 1_000_000_000,
    },
  },
  publication: {
    mode: "MANUAL_APPROVAL",
    visibility: "PUBLIC",
    labeling: {
      showAiGeneratedBadge: true,
      disclosureShort: "AI Analyst",
      disclosureLong:
        "This prediction was generated by an AI analyst account and reviewed before publication.",
    },
    cadence: {
      maxNewCallsPerRun: 5,
      maxNewCallsPerTradingDay: 5,
      mayPublishZeroCalls: true,
    },
    portfolio: {
      maxOpenPredictions: 20,
    },
  },
  generation: {
    provider: "openai",
    model: "gpt-5.4",
    promptVersion: "ai-chips-v1",
    outputVersion: "prediction-draft-v1",
    allowNoCall: true,
    evaluateUniverseAsBatch: true,
    requiredOutputFields: [
      "ticker",
      "direction",
      "thesisTitle",
      "thesis",
      "timeHorizon",
      "confidence",
      "catalyst",
      "signals",
      "risks",
    ],
  },
  guardrails: {
    openCallPolicy: {
      maxOpenCallsPerTicker: 1,
      blockDuplicateTickerWhileOpen: true,
    },
    approval: {
      requiresAdminReview: true,
    },
    confidence: {
      minPublishConfidence: 0.62,
    },
    thesis: {
      requireCatalyst: true,
      requireRiskSection: true,
      requireTimeHorizon: true,
      maxTitleLength: 120,
      maxBodyLength: 10000,
    },
    tickerEligibility: {
      onlyCoveredTickers: true,
    },
  },
  publicContent: {
    howItWorks: {
      summary:
        "AI Chips Analyst is an AI analyst account that reviews current open predictions and evaluates selective new ideas from its covered chip and infrastructure universe after end-of-day market processing completes.",
      methodology: [
        "Every run includes the analyst's current open predictions, so the model reasons from existing portfolio context rather than starting fresh each day.",
        "The analyst reviews the covered tickers that do not already have an open prediction and looks for selective setups with a clear directional thesis, catalyst, and time horizon.",
        "The model may return no new calls if the setup quality is not strong enough.",
      ],
      rules: [
        "The launch universe is currently focused on NVDA, AMD, AVGO, TSM, MU, and MRVL.",
        "Can have only one open call per ticker at a time.",
        "Can publish up to 5 new calls in a run, but may publish zero calls on days without strong setups.",
        "The total number of open AI analyst predictions should not exceed 20.",
        "All calls are labeled as AI Analyst predictions and reviewed before publication.",
      ],
      limitations: [
        "The analyst still depends on the structured market snapshot supplied by YouAnalyst and does not browse the live market on its own.",
        "It evaluates only the currently covered launch universe, not the full US market.",
        "Published calls reflect model output plus platform review, not certainty.",
        "A strong company is not automatically a daily call; timing and setup matter.",
      ],
    },
    profile: {
      coverageUniverseTitle: "Coverage Universe",
      methodologyTitle: "How This Analyst Works",
      limitationsTitle: "Limitations",
    },
  },
  internal: {
    scheduling: {
      trigger: "AFTER_EOD_COMPLETED",
      rerunPolicy: "IDEMPOTENT_SINGLE_RUN_PER_DAY",
    },
    prompting: {
      includeOpenCallsSummary: true,
      includeMarketSnapshot: true,
      includeEligibleTickersOnlyForPublication: true,
    },
    observability: {
      savePromptInput: true,
      saveRawModelOutput: true,
      saveValidationErrors: true,
    },
  },
};

const AI_ANALYST_CONFIGS: Record<AiAnalystId, AiAnalystConfig> = {
  [aiChipsAnalystConfig.id]: aiChipsAnalystConfig,
};

function readAiAnalystId(userData: Record<string, unknown> | null | undefined): AiAnalystId | null {
  const accountType = userData?.accountType;
  const aiAnalystId = userData?.aiAnalystId;

  if (accountType !== "AI_ANALYST" || typeof aiAnalystId !== "string") {
    return null;
  }

  return aiAnalystId in AI_ANALYST_CONFIGS ? (aiAnalystId as AiAnalystId) : null;
}

export function getAiAnalystConfig(id: AiAnalystId): AiAnalystConfig {
  return AI_ANALYST_CONFIGS[id];
}

export function getAiAnalystPublicProfile(id: AiAnalystId): PublicAiAnalystProfile {
  const config = getAiAnalystConfig(id);

  return {
    id: config.id,
    badgeLabel: config.identity.badgeLabel,
    theme: config.identity.theme,
    coverageTickers: [...config.coverage.tickers],
    disclosureShort: config.publication.labeling.disclosureShort,
    disclosureLong: config.publication.labeling.disclosureLong,
    howItWorks: config.publicContent.howItWorks,
    profileSections: config.publicContent.profile,
  };
}

export function getAiAnalystPublicProfileForUser(
  userData: Record<string, unknown> | null | undefined,
): PublicAiAnalystProfile | null {
  const id = readAiAnalystId(userData);
  return id ? getAiAnalystPublicProfile(id) : null;
}

